# Generated by Django 5.0.7 on 2024-07-31 07:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
