# Generated by Django 5.0.7 on 2024-08-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0004_continent_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="continent",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
