# Generated by Django 5.0.7 on 2024-08-02 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0005_alter_continent_name_alter_country_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="products_image")),
                ("denomination", models.CharField(max_length=150)),
                ("year", models.IntegerField()),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        choices=[("au", "gold"), ("ag", "silver")],
                        max_length=15,
                    ),
                ),
                (
                    "safety",
                    models.CharField(
                        blank=True,
                        choices=[("v", "v"), ("vf", "vf"), ("f", "f"), ("xf", "xf")],
                        max_length=2,
                    ),
                ),
                ("weight", models.FloatField(blank=True)),
                ("diameter", models.FloatField(blank=True)),
                ("thickness", models.FloatField(blank=True)),
                ("circulation", models.IntegerField(blank=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coins",
                        to="coins.country",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coin",
                "verbose_name_plural": "Coins",
            },
        ),
    ]
