# Generated by Django 5.0.7 on 2024-08-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0006_coin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin",
            name="circulation",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coin",
            name="diameter",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coin",
            name="thickness",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coin",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
