# Generated by Django 5.0.7 on 2024-08-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0008_box_coin_box"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin",
            name="material",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gold", "au"),
                    ("silver", "ag"),
                    ("platinum", "pt"),
                    ("palladium", "pd"),
                    ("copper", "cu"),
                    ("nickel", "ni"),
                    ("zinc", "zn"),
                    ("tin", "sn"),
                    ("bronze", "bronze"),
                    ("brass", "brass"),
                    ("cupronickel", "cupronickel"),
                    ("aluminum", "al"),
                    ("iron", "fe"),
                    ("lead", "pb"),
                    ("magnesium", "mg"),
                    ("magnetic metals", "magnetic metals"),
                    ("titanium", "ti"),
                ],
                max_length=15,
            ),
        ),
    ]
