# Generated by Django 5.0.7 on 2024-08-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0010_remove_coin_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="coin",
            name="img_add_1",
            field=models.ImageField(blank=True, upload_to="products_image"),
        ),
        migrations.AddField(
            model_name="coin",
            name="img_add_2",
            field=models.ImageField(blank=True, upload_to="products_image"),
        ),
        migrations.AddField(
            model_name="coin",
            name="img_back",
            field=models.ImageField(blank=True, upload_to="products_image"),
        ),
        migrations.AddField(
            model_name="coin",
            name="img_front",
            field=models.ImageField(blank=True, upload_to="products_image"),
        ),
    ]
