# Generated by Django 5.0.7 on 2024-08-06 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0011_coin_img_add_1_coin_img_add_2_coin_img_back_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("с", "under consideration"), ("d", "done")],
                        default="c",
                        max_length=1,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coin_to_get",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_get",
                        to="coins.coin",
                    ),
                ),
                (
                    "goin_to_give",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_give",
                        to="coins.coin",
                    ),
                ),
                (
                    "responder",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers_look",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
