# Generated by Django 5.0.7 on 2024-08-06 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0012_offer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offer",
            old_name="goin_to_give",
            new_name="coin_to_give",
        ),
    ]
