# Generated by Django 5.0.7 on 2024-08-07 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0013_rename_goin_to_give_offer_coin_to_give"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="coin_to_get",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offer_get",
                to="coins.coin",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="coin_to_give",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offer_give",
                to="coins.coin",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="responder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers_look",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
