# Generated by Django 5.0.7 on 2024-08-08 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0014_alter_offer_author_alter_offer_coin_to_get_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
