# Generated by Django 5.0.7 on 2024-08-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0016_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="coin",
            name="status",
            field=models.CharField(
                choices=[("a", "active"), ("e", "exchanged"), ("s", "sent")],
                default="a",
                max_length=1,
            ),
        ),
    ]
