# Generated by Django 5.0.7 on 2024-08-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0017_coin_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin",
            name="status",
            field=models.CharField(
                choices=[
                    ("a", "active"),
                    ("e", "exchanged"),
                    ("w", "wait for delivery"),
                    ("s", "sent"),
                ],
                default="a",
                max_length=1,
            ),
        ),
    ]
