# Generated by Django 5.0.7 on 2024-08-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0019_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="message",
            name="topic",
            field=models.CharField(default="without topic", max_length=128),
        ),
    ]
